
import pandas as pd

df = pd.read_csv("D:/Download Data/dairy_dataset.csv")
df


# In[33]:


# what is the average expiry day of each product.



avg_exp = df.groupby("Product Name").agg({"Shelf Life (days)":"mean"})
avg_exp


# In[39]:


# mention the name of product with max and min self life.


pr = df.groupby("Product Name").agg({"Shelf Life (days)":["min","max"]})

pr


# In[40]:


df.head()


# In[45]:


# summarize the data on the basis of brands and land acquired by them,cows and the revenue generated by them.

brands = df.groupby("Brand").agg({"Total Land Area (acres)":"sum","Number of Cows":"sum","Approx. Total Revenue(INR)":"sum"})

brands


# In[46]:


df.head()


# In[48]:


#. What is the average shelf life for different storage conditions. 

avg_sl = df.groupby("Storage Condition").agg({"Shelf Life (days)":"mean"})
avg_sl


# In[50]:


# what is location wise avg quanity production , quanity sold and revenue

loc_S = df.groupby("Location").agg({"Quantity (liters/kg)":"mean","Quantity Sold (liters/kg)":"mean","Approx. Total Revenue(INR)":"mean"})
loc_S


# In[55]:


# chanel wise the quantiy sold and revenue

ch = df.groupby("Sales Channel").agg({"Quantity Sold (liters/kg)":"sum","Price per Unit (sold)":"mean"})
ch

